[package]
name = "rust-3d"
version = "0.1.0"
authors = ["eduhenke <eduardo_henke@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
nalgebra = "0.22"
